#!/usr/bin/perl

use CGI qw/param/;
#use XML::LibXML;
use Encode;
use vars qw($ORACLE_HOME $ORACLE_SID);


#BEGIN
# {
  $ENV{ORACLE_HOME} = '/app/grid/product/12.1.0/dbhome_1';
  $ENV{NLS_LANG} = 'AMERICAN_AMERICA.UTF8';
 # $ENV{TNS_ADMIN} = '/app/grid/product/12.1.0/dbhome_1/network/admin';
# }
use DBI;
use DBD::Oracle qw( SQLCS_IMPLICIT SQLCS_NCHAR );
use CGI;


my $dbh=DBI->connect("dbi:Oracle:host=192.168.1.101;service_name=PDBORCL", "ticket_b2c", "qweqwe");

$dbh->{LongReadLen} = 524288 * 2;


#my $xdata =  decode utf8=>param('p_xml');


my $xdata = '<query>
<command>order_callback</command>
<payment_id>'.param('payment_id').'</payment_id>
<datetime>'.param('payment_id').'</datetime>
<status>'.param('status').'</status>
<extended_status>'.param('extended_status').'</extended_status>
<pp_identity>'.param('pp_identity').'</pp_identity>
<cf>'.param('cf').'</cf>
<cf2>'.param('cf2').'</cf2>
<cf3>'.param('cf3').'</cf3>
</query>';


my $res;

my $stmt="declare
begin
 :res := TICKET_B2C.TICKET_B2C_XML_INT.xml_request(xmltype(:xreq));
 end;";
my $rs=$dbh->prepare($stmt);
$rs->bind_param(":xreq",$xdata);
$rs->bind_param_inout(":res",\$res,0,{ ora_type => 112 });
$rs->execute();

$rs->finish;


print "Content-type: text/xml\n\n";
print $res;
