/*var STANDART = {
 ACTION_NAME:{
 object_type:'label',
 value:'',
 font_family:'Arial',
 font_size:'14',
 font_style:'normal',
 rotation:90,
 x:150,
 y:1500,
 w:20,
 h:15
 },
 LINE_PLACE:{
 items:['LINE',' : ','PLACE'],
 object_type:'label',
 value:'',
 font_family:'Arial',
 font_size:'14',
 font_style:'normal',
 rotation:90,
 x:100,
 y:1510,
 w:0,
 h:0
 }
 };*/
var templates = {
    'BARVIKHA':{
        'STANDART':{
            BARCODE:{
                object_type:'barcode',
                value:'',
                font_family:'Code39',
                font_size:'8',
                font_style:'normal',
                rotation:270,
                x:223,
                y:1984,
                w:560,
                h:125
            },
            ACTION_NAME_AND_AGE:{
                items:['ACTION_NAME','  (','AGE_CAT',')'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'18',
                font_style:'normal',
                rotation:270,
                x:403,
                y:1984,
                w:20,
                h:15
            },
            ACTION_DATE_TIME:{
                items:['Дата: ','ACTION_DATE', '   ', 'Время: ', 'ACTION_TIME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:270,
                x:350,
                y:1984,
                w:20,
                h:15
            },
            AREA_NAME:{

                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:270,
                x:500,
                y:1984,
                w:0,
                h:0
            },
            LINE_PLACE_AREA:{
                items:['LINE','  ','PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:270,
                x:550,
                y:1984,
                w:0,
                h:0
            },
            PRICE:{
                items:['Цена: ','PRICE',' руб. 00 коп.'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'12',
                font_style:'normal',
                rotation:270,
                x:600,
                y:1984,
                w:0,
                h:0
            },
            NDS:{
                object_type:'label',
                value:'В том числе и НДС',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:270,
                x:660,
                y:1984,
                w:0,
                h:0
            },
            Ticket_NO_LBL:{
                object_type:'label',
                value:'№ Билета:',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:270,
                x:660,
                y:1684,
                w:20,
                h:15
            },
            Ticket_NO:{
                items:['ORDER_TICKET_ID'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:270,
                x:660,
                y:1534,
                w:20,
                h:15
            },
            /*Корешок*/
            /*K1_LINE_PLACE_AREA:{
             items:['LINE','  ','PLACE'],
             object_type:'label',
             value:'',
             font_family:'Arial',
             font_size:'8',
             font_style:'normal',
             rotation:0,
             x:497,
             y:20,
             w:0,
             h:0
             },*/
            K1_ACTION_NAME_AND_AGE:{
                items:['ACTION_NAME','  (','AGE_CAT',')'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'8',
                font_style:'normal',
                rotation:180,
                x:524,
                y:2300,
                w:20,
                h:15
            },
            K1_USER:{
                items:['CASHER_NAME'],
                object_type:'label',
                value:'Кассир',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:740,
                y:2260,
                w:20,
                h:15
            },

            K1_DATA_TIME_LINE:{
                items:['ACTION_TIME',' ','ACTION_DATE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:740,
                y:2230,
                w:20,
                h:15
            },

            K1_PRICE_PLACE:{
                items:['Цена:',' ','PRICE',' руб. 00 коп.'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:740,
                y:2200,
                w:20,
                h:15
            },

            K1_NDS:{
                object_type:'label',
                value:'В том числе НДС',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:740,
                y:2170,
                w:20,
                h:15
            },
            K1_AREA:{
                items:['AREA_NAME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:390,
                y:2230,
                w:20,
                h:15
            },
            K1_LINE:{
                items:['LINE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:390,
                y:2200,
                w:20,
                h:15
            },
            K1_PLACE:{
                items:['PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:390,
                y:2170,
                w:20,
                h:15
            },
            K1_Ticket_NO_LBL:{
                object_type:'label',
                value:'№ Билета:',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:390,
                y:2140,
                w:20,
                h:15
            },
            K1_Ticket_NO:{
                items:['ORDER_TICKET_ID'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:390,
                y:2110,
                w:20,
                h:15
            },
            K1_Date:{
                items:['Дата: ','ACTION_DATE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'6',
                font_style:'normal',
                rotation:180,
                x:230,
                y:2140,
                w:20,
                h:15
            },
            K1_Time:{
                items:['Время: ','ACTION_TIME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'6',
                font_style:'normal',
                rotation:180,
                x:230,
                y:2110,
                w:20,
                h:15
            },
            K2_PRICE:{
                items:['Цена: ','PRICE',' руб. 00 коп.'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:387,
                y:200,
                w:0,
                h:0
            },
            K2_DATE:{
                items:['Дата: ','ACTION_DATE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:387,
                y:170,
                w:0,
                h:0
            },
            K2_TIME:{
                items:['Время: ','ACTION_TIME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:387,
                y:140,
                w:0,
                h:0
            },
            K2_NAME:{
                items:['ACTION_NAME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'8',
                font_style:'normal',
                rotation:180,
                x:387,
                y:80,
                w:0,
                h:0
            },
            K2_AGE:{
                items:['AGE_CAT'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'6',
                font_style:'normal',
                rotation:180,
                x:387,
                y:110,
                w:0,
                h:0
            },
            K2_LINE_PLACE_AREA:{
                items:['LINE','  ','PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:387,
                y:235,
                w:0,
                h:0
            },
            K2_AREA:{
                items:['AREA_NAME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:180,
                x:387,
                y:270,
                w:0,
                h:0
            }
        },
        'SUBSCRIPTION':{

            BARCODE:{
                object_type:'barcode',
                value:'',
                font_family:'Code39',
                font_size:'8',
                font_style:'normal',
                rotation:90,
                x:650,
                y:425,
                w:560,
                h:125

            },
            ACTION_NAME_AND_AGE:{
                items:['ACTION_NAME','  (','AGE_CAT',')'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'18',
                font_style:'normal',
                rotation:90,
                x:449,
                y:425,
                w:20,
                h:15
            },
            ACTION_DATE_TIME:{
                items:['Дата: ','ACTION_DATE', '   ', 'Время: ', 'ACTION_TIME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:90,
                x:507,
                y:425,
                w:20,
                h:15
            },
            AREA_NAME:{

                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:90,
                x:360,
                y:425,
                w:0,
                h:0
            },
            LINE_PLACE_AREA:{
                items:['LINE','  ','PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:90,
                x:300,
                y:425,
                w:0,
                h:0
            },
            PRICE:{
                items:['Цена: ','PRICE',' руб. 00 коп.'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'12',
                font_style:'normal',
                rotation:90,
                x:240,
                y:425,
                w:0,
                h:0
            },
            NDS:{
                object_type:'label',
                value:'В том числе и НДС',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:90,
                x:190,
                y:425,
                w:0,
                h:0
            },
            /*Корешок*/
            /*K1_LINE_PLACE_AREA:{
             items:['LINE','  ','PLACE'],
             object_type:'label',
             value:'',
             font_family:'Arial',
             font_size:'8',
             font_style:'normal',
             rotation:0,
             x:497,
             y:20,
             w:0,
             h:0
             },*/
            K1_ACTION_NAME_AND_AGE:{
                items:['ACTION_NAME','  (','AGE_CAT',')'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'8',
                font_style:'normal',
                rotation:0,
                x:350,
                y:75,
                w:20,
                h:15
            },
            K1_USER:{
                items:['CASHER_NAME'],
                object_type:'label',
                value:'ФИО Клиента',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:120,
                y:120,
                w:20,
                h:15
            },

            K1_DATA_TIME_LINE:{
                items:['ACTION_TIME',' ','ACTION_DATE',' ','LINE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:120,
                y:150,
                w:20,
                h:15
            },

            K1_PRICE_PLACE:{
                items:['Цена:',' ','PRICE',' руб. 00 коп.',' ','PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:120,
                y:180,
                w:20,
                h:15
            },

            K1_NDS:{
                object_type:'label',
                value:'В том числе НДС',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:120,
                y:210,
                w:20,
                h:15
            },
            K1_AREA:{
                items:['AREA_NAME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:480,
                y:150,
                w:20,
                h:15
            },
            K1_LINE:{
                items:['LINE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:480,
                y:180,
                w:20,
                h:15
            },
            K1_PLACE:{
                items:['PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:480,
                y:210,
                w:20,
                h:15
            },
            K1_Ticket_NO_LBL:{
                object_type:'label',
                value:'№ Билета:',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:480,
                y:240,
                w:20,
                h:15
            },
            K1_Ticket_NO:{
                items:['ORDER_TICKET_ID'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:480,
                y:270,
                w:20,
                h:15
            },
            K1_Date:{
                items:['Дата: ','ACTION_DATE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:640,
                y:240,
                w:20,
                h:15
            },
            K1_Time:{
                items:['Время: ','ACTION_TIME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:640,
                y:270,
                w:20,
                h:15
            },
            K2_PRICE:{
                items:['Цена: ','PRICE',' руб. 00 коп.'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:470,
                y:2160,
                w:0,
                h:0
            },
            K2_DATE:{
                items:['Дата: ','ACTION_DATE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:470,
                y:2190,
                w:0,
                h:0
            },
            K2_TIME:{
                items:['Время: ','ACTION_TIME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:470,
                y:2220,
                w:0,
                h:0
            },
            K2_NAME:{
                items:['ACTION_NAME'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'10',
                font_style:'normal',
                rotation:0,
                x:470,
                y:2250,
                w:0,
                h:0
            },
            K2_AGE:{
                items:['AGE_CAT'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:470,
                y:2290,
                w:0,
                h:0
            },
            K2_LINE_PLACE_AREA:{
                items:['LINE','  ','PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'7',
                font_style:'normal',
                rotation:0,
                x:470,
                y:2320,
                w:0,
                h:0
            }
        }

    },
    'MIR_BILETA':{
        'STANDART':{
            ACTION_NAME:{
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'12',
                font_style:'normal',
                rotation:90,
                x:455,
                y:278,
                w:20,
                h:15
            },
            ACTION_DATE_TIME:{
                items:['Дата: ','ACTION_DATE', '   ', 'Время: ', 'ACTION_TIME'],
                object_type:'label',
                value:'Дата:',
                font_family:'Arial',
                font_size:'12',
                font_style:'normal',
                rotation:90,
                x:356,
                y:278,
                w:20,
                h:15
            },
            LINE_PLACE_AREA:{
                items:['AREA_NAME','   ','LINE','  ','PLACE'],
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'12',
                font_style:'normal',
                rotation:90,
                x:289,
                y:429,
                w:0,
                h:0
            }
        },
        'SUBSCRIPTION':{
            ACTION_NAME:{
                object_type:'label',
                value:'',
                font_family:'Arial',
                font_size:'14',
                font_style:'normal',
                rotation:90,
                x:455,
                y:278,
                w:20,
                h:15
            }
        }

    }
};
// Мир билета 204
var STANDART = {
    ACTION_NAME:{
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:455,
        y:278,
        w:20,
        h:15
    },
    ACTION_DATE_TIME:{
        object_type:'label',
        value:'Дата:',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:280,
        y:190,
        w:20,
        h:15
    }
    /*,
     AREA_GROUP:{
     object_type:'label',
     value:'',
     font_family:'Arial',
     font_size:'14',
     font_style:'normal',
     rotation:90,
     x:343,
     y:429,
     w:20,
     h:15
     },
     BARCODE:{
     object_type:'barcode',
     value:'',
     font_family:'Code39',
     font_size:'14',
     font_style:'normal',
     rotation:90,
     x:677,
     y:512,
     w:360,
     h:110

     },
     HALL:{
     object_type:'label',
     value:'',
     font_family:'Arial',
     font_size:'14',
     font_style:'normal',
     rotation:90,
     x:343,
     y:429,
     w:20,
     h:15
     },
     LINE_PLACE:{
     items:['LINE',' : ','PLACE'],
     object_type:'label',
     value:'',
     font_family:'Arial',
     font_size:'14',
     font_style:'normal',
     rotation:90,
     x:294,
     y:429,
     w:0,
     h:0
     },
     PRICE:{
     object_type:'label',
     value:'',
     font_family:'Arial',
     font_size:'14',
     font_style:'normal',
     rotation:90,
     x:235,
     y:429,
     w:0,
     h:0
     },
     OKUN:{
     object_type:'label',
     value:'',
     font_family:'Arial',
     font_size:'1',
     font_style:'normal',
     rotation:0,
     x:10,
     y:10,w:20,h:15
     }*/

};
var SUBSCRIPTION = {
    ACTION_NAME:{
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:317,
        y:263,
        w:20,
        h:15
    },
    ACTION_DATE_TIME:{
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:198,
        y:263,
        w:20,
        h:15
    },
    AREA_GROUP:{
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:238,
        y:568,
        w:20,
        h:15
    },
    BARCODE:{
        object_type:'barcode',
        value:'',
        font_family:'Code39',
        font_size:'14',
        font_style:'normal',
        rotation:0,
        x:128,
        y:1296,
        w:360,
        h:100

    },
    HALL:{
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:238,
        y:568,
        w:20,
        h:15
    },
    LINE_PLACE:{
        items:['LINE',' : ','PLACE'],
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:118,
        y:263,
        w:0,
        h:0
    },
    PRICE:{
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'14',
        font_style:'normal',
        rotation:90,
        x:118,
        y:798,
        w:0,
        h:0
    },
    OKUN:{
        object_type:'label',
        value:'',
        font_family:'Arial',
        font_size:'1',
        font_style:'normal',
        rotation:0,
        x:10,
        y:10,w:20,h:15
    }

};

module.exports.templates = templates;
